[
{
id: 102,
title: "Lambda Welcome Center",
description: "The Lambda School journey begins here",
n_to: 103,
s_to: 0,
e_to: 0,
w_to: 0,
players: [
"joe",
"peterjacobstone",
],
},
{
id: 105,
title: "Campus Courtyard center",
description: "The middle grounds of Lambda's massive courtyard",
n_to: 104,
s_to: 103,
e_to: 106,
w_to: 107,
players: [ ],
},
{
id: 103,
title: "Campus Courtyard South",
description: "The south end of Lambda's massive courtyard",
n_to: 105,
s_to: 102,
e_to: 157,
w_to: 178,
players: [ ],
},
{
id: 106,
title: "Campus Courtyard East",
description: "The East end of Lambda's massive courtyard",
n_to: 115,
s_to: 122,
e_to: 129,
w_to: 105,
players: [ ],
},
{
id: 107,
title: "Campus Courtyard West",
description: "The West end of Lambda's massive courtyard",
n_to: 108,
s_to: 143,
e_to: 105,
w_to: 136,
players: [ ],
},
{
id: 104,
title: "Campus Courtyard North",
description: "The north end of Lambda's massive courtyard",
n_to: 164,
s_to: 105,
e_to: 150,
w_to: 171,
players: [ ],
},
{
id: 132,
title: "IOS Development Unit 2 Classroom",
description: "Here students study the second unit of IOS Development.",
n_to: 0,
s_to: 135,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 123,
title: "Android Development Help Center",
description: "Student's came here for an assist in android dev related work.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 122,
players: [ ],
},
{
id: 109,
title: "Data Science Help Center",
description: "Student's come here for an assist in data related work.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 108,
players: [ ],
},
{
id: 146,
title: "Computer Science Unit 2 Classroom",
description: "Here students study the second unit of Computer Science.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 149,
players: [ ],
},
{
id: 139,
title: "UX Design Unit 1 Classroom",
description: "Here students study the second unit of UX Design.",
n_to: 0,
s_to: 142,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 151,
title: "Lambda Labs Help Center",
description: "Student's come here for an assist in Computer Science related work.",
n_to: 0,
s_to: 150,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 161,
title: "Lambda Basketball Court",
description: "Students try to ball up here.(keyword=try)",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 160,
players: [ ],
},
{
id: 158,
title: "Lambda Gaming Center",
description: "Student's come here to win glory.",
n_to: 0,
s_to: 157,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 159,
title: "Lambda Cafeteria",
description: "Stay away from the chili...",
n_to: 157,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 160,
title: "Student Center Back Hallway",
description: "Leads to the back of the Student Center Building",
n_to: 163,
s_to: 162,
e_to: 161,
w_to: 157,
players: [ ],
},
{
id: 130,
title: "IOS Development Help Center",
description: "Student's come here for an assist in ios dev related work.",
n_to: 129,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 131,
title: "IOS Development Unit 1 Classroom",
description: "Here students study the first unit of IOS Development.",
n_to: 0,
s_to: 129,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 129,
title: "IOS Development Department Main Building",
description: "Here students come to learn about the wonders of Data.",
n_to: 131,
s_to: 130,
e_to: 135,
w_to: 106,
players: [ ],
},
{
id: 133,
title: "Data Science Unit 3 Classroom",
description: "Here students study the third unit of IOS Development.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 135,
players: [ ],
},
{
id: 134,
title: "Data Science Unit 4 Classroom",
description: "Here students study the fourth unit of IOS Development.",
n_to: 135,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 135,
title: "IOS Development Building Back Hallway",
description: "Leads to the back of the IOS Development Building where  the higher level classes are held",
n_to: 132,
s_to: 134,
e_to: 133,
w_to: 129,
players: [ ],
},
{
id: 116,
title: "Web Development Help Center",
description: "Student's come here for an assist in web dev related work.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 115,
players: [ ],
},
{
id: 117,
title: "Web Development Unit 1 Classroom",
description: "Here students study the first unit of web development.",
n_to: 0,
s_to: 0,
e_to: 115,
w_to: 0,
players: [ ],
},
{
id: 118,
title: "Web Development Unit 2 Classroom",
description: "Here students study the second unit of web development.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 121,
players: [ ],
},
{
id: 119,
title: "Web Development Unit 3 Classroom",
description: "Here students study the third unit of web development.",
n_to: 0,
s_to: 0,
e_to: 121,
w_to: 0,
players: [ ],
},
{
id: 120,
title: "Web Development Unit 4 Classroom",
description: "Here students study the fourth unit of web development.",
n_to: 0,
s_to: 121,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 121,
title: "Web Development Building Back Hallway",
description: "Leads to the back of the Web Development Building where  the higher level classes are held",
n_to: 120,
s_to: 115,
e_to: 118,
w_to: 119,
players: [ ],
},
{
id: 124,
title: "Android Development Unit 1 Classroom",
description: "Students used to study the first unit of Android Development here before the fire.",
n_to: 0,
s_to: 0,
e_to: 122,
w_to: 0,
players: [ ],
},
{
id: 125,
title: "Android Development Unit 2 Classroom",
description: "Students used to study the second unit of Android Development here before the fire.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 128,
players: [ ],
},
{
id: 122,
title: "Android Development Department Main Building Ruins",
description: "Here students used to come to learn about the wonders of Android Developmet before  it was destroyed in a fire.",
n_to: 106,
s_to: 128,
e_to: 123,
w_to: 124,
players: [ ],
},
{
id: 126,
title: "Android Development Unit 3 Classroom",
description: "Students used to study the third unit of Android Development here before the fire.",
n_to: 0,
s_to: 0,
e_to: 128,
w_to: 0,
players: [ ],
},
{
id: 127,
title: "Android Development Unit 4 Classroom",
description: "Students used to study the fourth unit of Android Development here before the fire.",
n_to: 128,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 128,
title: "Android Development Building Back Hallway Ruins",
description: "Leads to the back of the Android Development Building where  the higher level classes were held before the fire",
n_to: 122,
s_to: 127,
e_to: 125,
w_to: 126,
players: [ ],
},
{
id: 110,
title: "Data Science Unit 1 Classroom",
description: "Here students study the first unit of Data Science.",
n_to: 0,
s_to: 0,
e_to: 108,
w_to: 0,
players: [ ],
},
{
id: 111,
title: "Data Science Unit 2 Classroom",
description: "Here students study the second unit of Data Science.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 114,
players: [ ],
},
{
id: 108,
title: "Data Science Department Main Building",
description: "Here students come to learn about the wonders of Data.",
n_to: 114,
s_to: 107,
e_to: 109,
w_to: 110,
players: [ ],
},
{
id: 112,
title: "Data Science Unit 3 Classroom",
description: "Here students study the third unit of Data Science.",
n_to: 0,
s_to: 0,
e_to: 114,
w_to: 0,
players: [ ],
},
{
id: 113,
title: "Data Science Unit 4 Classroom",
description: "Here students study the fourth unit of Data Science.",
n_to: 0,
s_to: 114,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 114,
title: "Data Science Building Back Hallway",
description: "Leads to the back of the Data Science Building where  the higher level classes are held",
n_to: 113,
s_to: 108,
e_to: 111,
w_to: 112,
players: [ ],
},
{
id: 148,
title: "Unit 2 Gallery",
description: "A wonderful gallery displaying the amazing projects built in the second build week of Lambda's Computer Science Program.",
n_to: 0,
s_to: 0,
e_to: 143,
w_to: 0,
players: [ ],
},
{
id: 143,
title: "Computer Science Department Main Building",
description: "Here students come to learn about the wonders of Computer Science.",
n_to: 107,
s_to: 149,
e_to: 147,
w_to: 148,
players: [ ],
},
{
id: 145,
title: "Computer Science Unit 1 Classroom",
description: "Here students study the first unit of Computer Science.",
n_to: 0,
s_to: 0,
e_to: 149,
w_to: 0,
players: [ ],
},
{
id: 144,
title: "Computer Science Help Center",
description: "Student's come here for an assist in Computer Science related work.",
n_to: 149,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 149,
title: "Computer Science Building Back Hallway",
description: "Leads to the back of the Computer Science Building",
n_to: 143,
s_to: 144,
e_to: 146,
w_to: 145,
players: [ ],
},
{
id: 137,
title: "UX Design Help Center",
description: "Student's come here for an assist in ios dev related work.",
n_to: 136,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 138,
title: "UX Design Unit 1 Classroom",
description: "Here students study the first unit of UX Design.",
n_to: 0,
s_to: 136,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 136,
title: "UX Design Department Main Building",
description: "Here students come to learn about the wonders of UX Design.",
n_to: 138,
s_to: 137,
e_to: 107,
w_to: 142,
players: [ ],
},
{
id: 140,
title: "UX Design Unit 1 Classroom",
description: "Here students study the third unit of UX Design.",
n_to: 0,
s_to: 0,
e_to: 142,
w_to: 0,
players: [ ],
},
{
id: 141,
title: "UX Design Unit 4 Classroom",
description: "Here students study the fourth unit of UX Design.",
n_to: 142,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 142,
title: "UX Design Building Back Hallway",
description: "Leads to the back of the UX Design Building where  the higher level classes are held",
n_to: 139,
s_to: 141,
e_to: 136,
w_to: 140,
players: [ ],
},
{
id: 152,
title: "Lambda Labs Team Room",
description: "Teams use this room to plan and execute their ideas.",
n_to: 150,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 154,
title: "Lambda Labs Data Science Gallery",
description: "A wonderful gallery displaying the amazing projects built in Lambda Labs with a Data Science focus.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 153,
players: [ ],
},
{
id: 150,
title: "Lambda Labs Department Main Building",
description: "Here students come to grind along other developers on extensive projects getting true real world experience.",
n_to: 151,
s_to: 152,
e_to: 153,
w_to: 104,
players: [ ],
},
{
id: 156,
title: "Lambda Labs Mobile Gallery",
description: "A wonderful gallery displaying the amazing projects built in Lambda Labs with a Mobile App focus.",
n_to: 0,
s_to: 153,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 155,
title: "Lambda Labs Web Gallery",
description: "A wonderful gallery displaying the amazing projects built in Lambda Labs with a Web App focus.",
n_to: 153,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 153,
title: "Lambda Labs Building Back Hallway",
description: "Leads to the back of the Lambda Labs Building where it's galleries are held",
n_to: 156,
s_to: 155,
e_to: 154,
w_to: 150,
players: [ ],
},
{
id: 163,
title: "Lambda Gym",
description: "Students can pump iron here.",
n_to: 0,
s_to: 160,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 186,
title: "Student Housing Kitchen",
description: "Students try to make their own food here.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 182,
players: [ ],
},
{
id: 179,
title: "Community Gardens",
description: "Community garden right off the path to campus housing making easy access to fresh vegetables and herbs",
n_to: 0,
s_to: 178,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 181,
title: "Campus Housing Square",
description: "Square connecting all the Campus housing to the rest of campus",
n_to: 183,
s_to: 182,
e_to: 178,
w_to: 184,
players: [ ],
},
{
id: 180,
title: "Recreation Fields",
description: "Massive grass field used for extracurricular activities like soccer and football. ",
n_to: 178,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 178,
title: "Housing Path",
description: "The path leading towards campus housing, passing  the Community Gardens and the Recreation Fields",
n_to: 179,
s_to: 180,
e_to: 103,
w_to: 181,
players: [ ],
},
{
id: 197,
title: "Administration Housing Lounge",
description: "Administration come here to chill.",
n_to: 184,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 162,
title: "Lambda Pool",
description: "Students can swim here",
n_to: 160,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 191,
title: "Staff Housing Lounge",
description: "Staff come here to chill.",
n_to: 0,
s_to: 0,
e_to: 183,
w_to: 0,
players: [ ],
},
{
id: 166,
title: "Lambda Teacher Lounge",
description: "Teachers hide from students here.",
n_to: 0,
s_to: 0,
e_to: 164,
w_to: 0,
players: [ ],
},
{
id: 176,
title: "Data Science Career Office",
description: "Student's come here for Data Science related career questions.",
n_to: 0,
s_to: 0,
e_to: 177,
w_to: 0,
players: [ ],
},
{
id: 164,
title: "Lambda Administration Department Main Building",
description: "Lambda Employees main place of operation.",
n_to: 170,
s_to: 104,
e_to: 165,
w_to: 166,
players: [ ],
},
{
id: 169,
title: "Ben Nelson's Office",
description: "Here is where Ben is Ben.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 170,
players: [ ],
},
{
id: 157,
title: "Lambda Student Center Building",
description: "Here students come in the rare occurences they aren't behind their computer.",
n_to: 158,
s_to: 159,
e_to: 160,
w_to: 103,
players: [ ],
},
{
id: 115,
title: "Web Development Department Main Building",
description: "Here students come to learn about the wonders of full stack web development.",
n_to: 121,
s_to: 106,
e_to: 116,
w_to: 117,
players: [ ],
},
{
id: 147,
title: "Unit 1 Gallery",
description: "A wonderful gallery displaying the amazing projects built in the first build week of Lambda's Computer Science Program.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 143,
players: [ ],
},
{
id: 182,
title: "Lambda Student Housing",
description: "This is the main part of the student housing building.",
n_to: 181,
s_to: 187,
e_to: 186,
w_to: 185,
players: [ ],
},
{
id: 165,
title: "Lambda Team Lead Lounge",
description: "Team Leads little getaway.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 164,
players: [ ],
},
{
id: 174,
title: "IOS Career Office",
description: "Student's come here for IOS related career questions.",
n_to: 0,
s_to: 177,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 167,
title: "Ryan Allred's Office",
description: "Here is where Ryan romes.",
n_to: 0,
s_to: 170,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 177,
title: "Administration Building Back Hallway",
description: "Leads to the back of the Admin Building",
n_to: 174,
s_to: 175,
e_to: 171,
w_to: 176,
players: [ ],
},
{
id: 168,
title: "Austen Allred's Office",
description: "Here is where Austen get's it done.",
n_to: 0,
s_to: 0,
e_to: 170,
w_to: 0,
players: [ ],
},
{
id: 170,
title: "Administration Building Back Hallway",
description: "Leads to the back of the Admin Building",
n_to: 167,
s_to: 164,
e_to: 169,
w_to: 168,
players: [ ],
},
{
id: 172,
title: "Careers Help Office",
description: "Here students can pop in for general career questions",
n_to: 0,
s_to: 171,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 171,
title: "Lambda Careers Building",
description: "Here students come for help on the job search.",
n_to: 172,
s_to: 173,
e_to: 104,
w_to: 177,
players: [ ],
},
{
id: 173,
title: "UX Career Office",
description: "Student's come here for UX related career questions.",
n_to: 171,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 185,
title: "Student Housing Lounge",
description: "Students come here to chill.",
n_to: 0,
s_to: 0,
e_to: 182,
w_to: 0,
players: [ ],
},
{
id: 175,
title: "Web Career Office",
description: "Student's come here for Web related career questions.",
n_to: 177,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 187,
title: "Student Housing Back Hall",
description: "Hall provides access to the different housing wings",
n_to: 182,
s_to: 190,
e_to: 188,
w_to: 189,
players: [ ],
},
{
id: 190,
title: "Student Housing Charlie Wing",
description: "How those living in the Charlie Wing of the Student Building  access their Quarters. You must be living here to go further.",
n_to: 187,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 196,
title: "Staff Housing Charlie Wing",
description: "How those living in the Charlie Wing of the Staff Building  access their Quarters. You must be living here to go further.",
n_to: 0,
s_to: 193,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 188,
title: "Student Housing Alpha Wing",
description: "How those living in the Alpha Wing of the Student Building  access their Quarters. You must be living here to go further.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 187,
players: [ ],
},
{
id: 194,
title: "Staff Housing Alpha Wing",
description: "How those living in the Alpha Wing of the Staff Building  access their Quarters. You must be living here to go further.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 193,
players: [ ],
},
{
id: 189,
title: "Student Housing Beta Wing",
description: "How those living in the Beta Wing of the Student Building  access their Quarters. You must be living here to go further.",
n_to: 0,
s_to: 0,
e_to: 187,
w_to: 0,
players: [ ],
},
{
id: 202,
title: "Administration Housing Charlie Wing",
description: "How those living in the Charlie Wing of the Administration Building  access their Quarters. You must be living here to go further.",
n_to: 199,
s_to: 0,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 192,
title: "Staff Housing Kitchen",
description: "Staff make their own food here.",
n_to: 0,
s_to: 0,
e_to: 0,
w_to: 183,
players: [ ],
},
{
id: 183,
title: "Lambda Staff Housing",
description: "This is the main part of the staff housing building.",
n_to: 193,
s_to: 181,
e_to: 192,
w_to: 191,
players: [ ],
},
{
id: 195,
title: "Staff Housing Beta Wing",
description: "How those living in the Beta Wing of the Staff Building  access their Quarters. You must be living here to go further.",
n_to: 0,
s_to: 0,
e_to: 193,
w_to: 0,
players: [ ],
},
{
id: 193,
title: "Staff Housing Back Hall",
description: "Hall provides access to the different staff housing wings",
n_to: 196,
s_to: 183,
e_to: 194,
w_to: 195,
players: [ ],
},
{
id: 200,
title: "Administration Housing Alpha Wing",
description: "How those living in the Alpha Wing of the Administration Building  access their Quarters. You must be living here to go further.",
n_to: 0,
s_to: 199,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 198,
title: "Administration Housing Kitchen",
description: "Administration make their own food here.",
n_to: 0,
s_to: 184,
e_to: 0,
w_to: 0,
players: [ ],
},
{
id: 184,
title: "Lambda Administration Housing",
description: "This is the main part of the administration housing building.",
n_to: 198,
s_to: 197,
e_to: 181,
w_to: 199,
players: [ ],
},
{
id: 201,
title: "Administration Housing Beta Wing",
description: "How those living in the Beta Wing of the Administration Building  access their Quarters. You must be living here to go further.",
n_to: 0,
s_to: 0,
e_to: 199,
w_to: 0,
players: [ ],
},
{
id: 199,
title: "Administration Housing Back Hall",
description: "Hall provides access to the different administration housing wings",
n_to: 200,
s_to: 202,
e_to: 184,
w_to: 201,
players: [ ],
},
]